services:
  - react-app

language: generic

before_install:
  - docker build -t zafergenc/react-app-test -f Dockerfile.dev .

script:
  - docker run -e CI=true zafergenc/react-app-test npm run test -- --coverage

